spring:
  datasource:
    jdbc-url: "jdbc:h2:mem:/~/test;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;"
    url: "mem:/~/test;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;"
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
  server:
    port:
      web: 8082
      tcp: 8084
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
