spring:
  profiles.active: dev,h2,security
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    root: INFO
keepup:
  paths:
    static1: /app/static
  server:
    resources:
      worker_count: ${KEEPUP_SERVER_RESOURCES_WORKER_COUNT:#{16}}