spring:
  datasource:
    url: "jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1"
    driver-class-name: org.h2.Driver
    driverClassName: org.h2.Driver
    username: sa
    password: ""
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: true
    change-log: "classpath:db/changelog/db.changelog-master.yaml"
